#spring:
#  application:
#    name: interview-scheduler
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/prabhakar
#    username: postgres
#    password: Prabha@225
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        format_sql: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: @gmail.com
    password: password
    smtp:
      connectiontimeout: 5000
      timeout: 5000
      witetimeout: 5000
      auth: true
      starttls:
        enable: true
      ssl:
        enable: false
    debug: true
